sudo: false
language: scala

scala:
  - 2.12.4

jdk:
  - oraclejdk8

# microsites
before_install:
  - export PATH=${PATH}:./vendor/bundle

# microsites
install:
  - rvm use 2.2.8 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.2.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION docs/makeMicrosite

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.coursier/cache
    - $HOME/.sbt